### ISSUE TITLE
sock_ops: program should be able to return a negative value

### ISSUE THREAD

**Issue by l2dy** [aya-rs/aya#1019]
https://github.com/aya-rs/aya/blob/40f303205f7a800877fe3f9a4fb1893141741e13/aya-ebpf-macros/src/sock_ops.rs#L26

The `sock_ops` proc macro generates a function that returns `u32`, but the commit[[1]] that added BPF support for sock_ops to Linux says (emphasis mine):

> Currently there are two types of ops. The first type expects the BPF program to return a value which is then used by the caller (or a **negative value** to indicate the operation is not supported). The second type expects state changes to be done by the BPF program, for example through a setsockopt BPF helper function, and they ignore the return value.

Should we change the return type to i32?

[1]: https://github.com/torvalds/linux/commit/40304b2a1567fecc321f640ee4239556dd0f3ee0

**Comment by alessandrod** [comment]
Sounds like we should! Have you double checked in the kernel that callers still handle < 0 return values?
