### ISSUE TITLE
When I create a simple kprobe demo project by aya-template. error occured  Error: `perf_event_open` failed

### ISSUE THREAD

**Issue by FlorentinoJink** [aya-rs/aya#1077]
In My VMware machine Ununtu 22.04
kernel version: 6.5.0-18-generic

I using the command  
```shell
cargo generate --name scan-kprobe -d program_type=kprobe https://github.com/aya-rs/aya-template
```
to create a simple kprobe demo application.

And then, I using  
```shell 
cargo run --release --config 'target."cfg(all())".runner="sudo -E"'
```
to run the demo app.  
![image](https://github.com/user-attachments/assets/a3c5404a-fcfd-4403-be8b-cb2f33851f9e)

So I using  
```shell
sudo strace -f -e trace=perf_event_open ./target/debug/scan-kprobe
```
strace: Process 36483 attached
strace: Process 36484 attached
strace: Process 36485 attached
strace: Process 36486 attached
strace: Process 36487 attached
strace: Process 36488 attached
strace: Process 36489 attached
strace: Process 36490 attached
[pid 36482] perf_event_open({type=PERF_TYPE_SOFTWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_BPF_OUTPUT, sample_period=1, sample_type=PERF_SAMPLE_RAW, read_format=0, precise_ip=0 /* arbitrary skid */, ...}, -1, 0, -1, PERF_FLAG_FD_CLOEXEC) = 12
[pid 36482] perf_event_open({type=PERF_TYPE_SOFTWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_BPF_OUTPUT, sample_period=1, sample_type=PERF_SAMPLE_RAW, read_format=0, precise_ip=0 /* arbitrary skid */, ...}, -1, 1, -1, PERF_FLAG_FD_CLOEXEC) = 13
[pid 36482] perf_event_open({type=PERF_TYPE_SOFTWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_BPF_OUTPUT, sample_period=1, sample_type=PERF_SAMPLE_RAW, read_format=0, precise_ip=0 /* arbitrary skid */, ...}, -1, 2, -1, PERF_FLAG_FD_CLOEXEC) = 14
[pid 36482] perf_event_open({type=PERF_TYPE_SOFTWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_BPF_OUTPUT, sample_period=1, sample_type=PERF_SAMPLE_RAW, read_format=0, precise_ip=0 /* arbitrary skid */, ...}, -1, 3, -1, PERF_FLAG_FD_CLOEXEC) = 15
[pid 36482] perf_event_open({type=PERF_TYPE_SOFTWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_BPF_OUTPUT, sample_period=1, sample_type=PERF_SAMPLE_RAW, read_format=0, precise_ip=0 /* arbitrary skid */, ...}, -1, 4, -1, PERF_FLAG_FD_CLOEXEC) = 16
[pid 36482] perf_event_open({type=PERF_TYPE_SOFTWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_BPF_OUTPUT, sample_period=1, sample_type=PERF_SAMPLE_RAW, read_format=0, precise_ip=0 /* arbitrary skid */, ...}, -1, 5, -1, PERF_FLAG_FD_CLOEXEC) = 17
[pid 36482] perf_event_open({type=PERF_TYPE_SOFTWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_BPF_OUTPUT, sample_period=1, sample_type=PERF_SAMPLE_RAW, read_format=0, precise_ip=0 /* arbitrary skid */, ...}, -1, 6, -1, PERF_FLAG_FD_CLOEXEC) = 18
[pid 36482] perf_event_open({type=PERF_TYPE_SOFTWARE, size=0x88 /* PERF_ATTR_SIZE_??? */, config=PERF_COUNT_SW_BPF_OUTPUT, sample_period=1, sample_type=PERF_SAMPLE_RAW, read_format=0, precise_ip=0 /* arbitrary skid */, ...}, -1, 7, -1, PERF_FLAG_FD_CLOEXEC) = 19
[pid 36482] perf_event_open({type=0x8 /* PERF_TYPE_??? */, size=0x88 /* PERF_ATTR_SIZE_??? */, config=0, sample_period=0, sample_type=0, read_format=0, precise_ip=0 /* arbitrary skid */, ...}, -1, 0, -1, PERF_FLAG_FD_CLOEXEC) = -1 ENOENT (没有那个文件或目录)
[pid 36487] +++ exited with 0 +++
[pid 36485] +++ exited with 0 +++
[pid 36490] +++ exited with 0 +++
[pid 36484] +++ exited with 0 +++
[pid 36488] +++ exited with 0 +++
[pid 36486] +++ exited with 0 +++
[pid 36483] +++ exited with 0 +++
[pid 36489] +++ exited with 0 +++
Error: `perf_event_open` failed

Caused by:
    No such file or directory (os error 2)
+++ exited with 1 +++

**Comment by FlorentinoJink** [comment]
There is the debug info
![image](https://github.com/user-attachments/assets/911b6224-f7b2-4358-9ba3-660be49870a2)

**Comment by dave-tucker** [comment]
Which function are you trying to trace?
Usually logs like this indicate the function you're trying to attach a kprobe to is incorrect, or unavailable for tracing.

**Comment by FlorentinoJink** [comment]
> Which function are you trying to trace? Usually logs like this indicate the function you're trying to attach a kprobe to is incorrect, or unavailable for tracing.

I want to trace the 
`sys_openat`
`sys_open`
`sys_getdents64`
`sys_getdents`
functions.
What should I do? And How to get the kprobe support function lists? 

Thanks.

**Comment by FlorentinoJink** [comment]
I using `trace-cmd` found the kprobe support functions, thanks again.
