### ISSUE TITLE
Unsupported map type warning message doesn't go away when unsupported type maps are allowed

### ISSUE THREAD

**Issue by banditopazzo** [aya-rs/aya#1081]
I was trying to load an unsupported map type and I got the following error:

```console
The map my_task_storage is of type BPF_MAP_TYPE_TASK_STORAGE which is currently unsupported in Aya, use `allow_unsupported_maps()` to load it anyways
```

and my program crashes with something like:

```console
Unsupported map type found 29
```

and it's OK. 

Then I added `allow_unsupported_maps()` to `BpfLoader` it loads the program without crashing but prints again:

```console
The map my_task_storage is of type BPF_MAP_TYPE_TASK_STORAGE which is currently unsupported in Aya, use `allow_unsupported_maps()` to load it anyways
```

**Comment by tyrone-wu** [comment]
Yah. The message could use some tweaking, or removed, when loading an unsupported map in aya with `allow_unsupported_maps()` specified.

The [`parse_map()`](https://github.com/aya-rs/aya/blob/main/aya/src/bpf.rs#L698) function could probably be inlined like how `programs` is done.
