### ISSUE TITLE
xdp_hello example fails verifier in docker rust container

### ISSUE THREAD

**Issue by esemeniuc** [aya-rs/aya#1104]
Running the [xdp_hello](https://github.com/aya-rs/book/tree/main/examples/xdp-hello) example with the following commands fails in:

`docker run -it --privileged --network host --rm -v ~/dev/aya-book:/myapp -w /myapp rust bash`

Inside the container, I ran:
```bash
rustup install nightly
rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
cargo install bpf-linker
cd examples/xdp-hello/
cargo xtask build-ebpf
```

Output
```
   Compiling xdp-hello-common v0.1.0 (/myapp/examples/xdp-hello/xdp-hello-common)
   Compiling xdp-hello v0.1.0 (/myapp/examples/xdp-hello/xdp-hello)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 6.26s
Error: the BPF_PROG_LOAD syscall failed. Verifier output: last insn is not an exit or jmp
verification time 9 usec
stack depth 0+0+0
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0


Caused by:
    Invalid argument (os error 22)
```

Host OS: arch running `6.6.52-1-lts`

**Comment by esemeniuc** [comment]
Issue: `info!` calls must be removed. The demo is broken due to that. See https://discord.com/channels/855676609003651072/1310568860738388059/1312632243574931517

**Comment by tamird** [comment]
Does it work if you use `--release`?

**Comment by tamird** [comment]
The template and book have been updated to only build ebpf in release mode. Please file an issue against those if you continue to be able to reproduce.

**Comment by esemeniuc** [comment]
Yes this works, thank you very much
```
rustup install nightly
rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
cargo install bpf-linker
cd examples/xdp-hello/
cargo xtask build-ebpf --release
cargo build --release
```
