### ISSUE TITLE
Can aya load map from pin file?

### ISSUE THREAD

**Issue by d0u9** [aya-rs/aya#155]
For maps used by classifier, does aya support loading map from pin file?

**Comment by dave-tucker** [comment]
yes it does! see: [map_pin_path](https://docs.rs/aya/latest/aya/struct.BpfLoader.html#method.map_pin_path)
you also need to set `pinning: PinningType::PinByName` in your map definition.

once done, `BpfLoader` will check if `$path/$map_name` exists and if it does, it will use the pinned map
