### ISSUE TITLE
Test loading programs written in C

### ISSUE THREAD

**Issue by vadorovsky** [aya-rs/aya#180]
Recently we were hitting multiple issues when trying to load eBPF programs written in C from projects like:

* https://github.com/nimrodshn/packetfilter
* https://github.com/rancher-sandbox/lockc

Those issues were being fixed step by step by #171, #173, #174, #177, #179.

However, to ensure that Aya really supports loading eBPF programs written in C and to avoid issues in future, we need to test.

The idea is to:

* try to use https://rust-script.org/ (we probably don't want to use regular Rust tests for that)
* compile C modules with clang
* use embedded libbpf headers from https://crates.io/crates/libbpf-sys

**Comment by dave-tucker** [comment]
Related PR: #160
