### ISSUE TITLE
Remove never_type dependency from user space build [when using bindings]

### ISSUE THREAD

**Issue by tmtiwari** [aya-rs/aya#184]
[https://github.com/aya-rs/aya/commit/df26fd94a74d40069d10cd448adf4e7c27ede26a](https://github.com/aya-rs/aya/commit/df26fd94a74d40069d10cd448adf4e7c27ede26a) introduced the `nightly` build dependency for user space since `bindings` is common to `aya` user space and `aya-bpf` kernel space.

**Comment by tamird** [comment]
I don't understand this issue. User space builds on stable. Please comment if this affects you.

**Comment by tmtiwari** [comment]
It was an old issue from last year. I don’t think it’s an issue anymore.
