### ISSUE TITLE
Make bindings ctypes prefix configurable

### ISSUE THREAD

**Issue by tmtiwari** [aya-rs/aya#186]
Currently bindings have hardcoded ctypes. See https://github.com/aya-rs/aya/pull/185 and https://github.com/aya-rs/aya/commit/ca14306860cbbb28563137c042fd0249d780bbb9

This enhancements will:

- Default bindings for `eBPF` to use `::aya_bpf::cty`
- Default bindings for `Userspace` to use `aya_bpf_cty`
- Default bindings for `Common` to use `aya_bpf_cty`
- Allow end users to specify whether the bindings are for 1) Kernel Space, or 2) User Space, or 3) Common

**Comment by alessandrod** [comment]
I think we should probably make the prefix string configurable as an option as part of https://github.com/aya-rs/aya/issues/95
