### ISSUE TITLE
Remove the need to use `static mut` for maps

### ISSUE THREAD

**Issue by vadorovsky** [aya-rs/aya#233]
Currently we require BPF maps to be `static mut`, which is a bad practice. To remove that necessity, we would most likely need to make maps to implement `Sync` and try to not use mutable reference in methods like:

https://github.com/aya-rs/aya/blob/b655cf973f639c685dc22ac30fe9dbffef31304a/bpf/aya-bpf/src/maps/hash_map.rs#L38-L41

From my understanding, the major reason we need muts there is that helpers like `bpf_map_update_elem` take non-const pointers to `bpf_map_update_elem`, but I don't think they actually modify that struct.

**Comment by ishitatsuyuki** [comment]
I'd like to work on this. Is there anything I need to take care of apart from changing the methods to take &self and casting the pointers from *const to *mut?
