### ISSUE TITLE
implement remaining cgroup program types

### ISSUE THREAD

**Issue by Arnab035** [aya-rs/aya#26]
The list of BPF cgroup program types are as follows -

- [x] BPF_PROG_TYPE_CGROUP_SKB
- [x] BPF_PROG_TYPE_CGROUP_SOCK
- [ ] BPF_PROG_TYPE_CGROUP_DEVICE
- [x] BPF_PROG_TYPE_CGROUP_SOCK_ADDR
- [x] BPF_PROG_TYPE_CGROUP_SYSCTL
- [x] BPF_PROG_TYPE_CGROUP_SOCKOPT

The program type BPF_PROG_TYPE_CGROUP_SKB has already been implemented [here](https://docs.rs/aya/0.10.2/aya/programs/struct.CgroupSkb.html). This issue will track the development of the remaining program types.

**Comment by alessandrod** [comment]
We've implemented all of them except DEVICE, which is tracked here https://github.com/aya-rs/aya/issues/212
