### ISSUE TITLE
Bpf::load fail in wsl (ubuntu 20.04)

### ISSUE THREAD

**Issue by jm-observer** [aya-rs/aya#302]
hello, when i try run user-space app according to [tutorial](https://aya-rs.github.io/book/start/hello-xdp.html) in wsl, bpf load fail and  report a error:

```
09:36:40 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:106] [FEAT PROBE] BPF program name support: true
09:36:40 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:109] [FEAT PROBE] BTF support: true
09:36:40 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:113] [FEAT PROBE] BTF func support: true
09:36:40 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:116] [FEAT PROBE] BTF global func support: true
09:36:40 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:122] [FEAT PROBE] BTF var and datasec support: true
09:36:40 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:128] [FEAT PROBE] BTF float support: false
09:36:40 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:131] [FEAT PROBE] BTF decl_tag support: false
09:36:40 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:134] [FEAT PROBE] BTF type_tag support: false
Error: map error

Caused by:
    0: failed to create map `AYA_LOG_BUF` with code -1
    1: Operation not permitted (os error 1)
```

now, how i should to resolve it?

**Comment by ishitatsuyuki** [comment]
What’s your kernel version?

**Comment by jm-observer** [comment]
> What’s your kernel version?

Linux LAPTOP-U56930FU 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jm-observer** [comment]
hello, now i install the linux_header, but it also report this error, Should I set any environment variables?

```
jmhuang@LAPTOP-U56930FU:/lib/modules$ tree -L 3  5.10.16.3-microsoft-standard-WSL2/
5.10.16.3-microsoft-standard-WSL2/
├── build -> /home/jmhuang/WSL2-Linux-Kernel-linux-msft-wsl-5.10.16.3
├── kernel
├── modules.alias
├── modules.alias.bin
├── modules.builtin
├── modules.builtin.alias.bin
├── modules.builtin.bin
├── modules.builtin.modinfo
├── modules.dep
├── modules.dep.bin
├── modules.devname
├── modules.order
├── modules.softdep
├── modules.symbols
├── modules.symbols.bin
└── source -> /home/jmhuang/WSL2-Linux-Kernel-linux-msft-wsl-5.10.16.3

3 directories, 13 files
```

**Comment by jm-observer** [comment]
Maybe I should upgrade the kernel to [Linux-MSFT-WSL-5.10.74.3](https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.10.74.3) ?

**Comment by ishitatsuyuki** [comment]
If you haven’t done it yet, you should do so.

**Comment by jm-observer** [comment]
hello, it doesn't work: 

```
14:28:48 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:106] [FEAT PROBE] BPF program name support: true
14:28:48 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:109] [FEAT PROBE] BTF support: true
14:28:48 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:113] [FEAT PROBE] BTF func support: true
14:28:48 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:116] [FEAT PROBE] BTF global func support: true
14:28:48 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:122] [FEAT PROBE] BTF var and datasec support: true
14:28:48 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:128] [FEAT PROBE] BTF float support: false
14:28:48 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:131] [FEAT PROBE] BTF decl_tag support: false
14:28:48 [DEBUG] (1) aya::bpf: [/home/jmhuang/.cargo/git/checkouts/aya-c55fbc69175ac116/79e06f2/aya/src/bpf.rs:134] [FEAT PROBE] BTF type_tag support: false
Error: map error

Caused by:
    0: failed to create map `AYA_LOG_BUF` with code -1
    1: Operation not permitted (os error 1)
jmhuang@LAPTOP-U56930FU:~/git/myapp$ uname -r
5.10.93.2-microsoft-standard-WSL2
jmhuang@LAPTOP-U56930FU:~/git/myapp$ tree -L 3 -d /lib/modules/5.10.93.2-microsoft-standard-WSL2/
/lib/modules/5.10.93.2-microsoft-standard-WSL2/
├── build -> /home/jmhuang/WSL2-Linux-Kernel-linux-msft-wsl-5.10.93.2
├── kernel
└── source -> /home/jmhuang/WSL2-Linux-Kernel-linux-msft-wsl-5.10.93.2

3 directories
```

**Comment by Matthias247** [comment]
I run into the same yesterday, and was able to work around it using the following hints:

https://prototype-kernel.readthedocs.io/en/latest/bpf/troubleshooting.html

This indicates that the operation might fail due to `RLIMIT_MEMLOCK `  being too low. I tried changing the limit system wide via `ulimit -l`, but that didn't work (only allowed to increase the limit).
Then I read through some threads like https://bbs.archlinux.org/viewtopic.php?id=244525 and figured out I can increase it by editing `/etc/security/limits.conf`. Placing the following line there and logging in again as `so root` increased the limit (one can confirm via running `ulimit -l`) and makes my aya example run (at least as root user):
```
root             -       memlock         131072
```

As the first link mentioned, it might also be fixable via calling [setrlimit](https://man7.org/linux/man-pages/man2/setrlimit.2.html) in the application - but I didn't investigate that further so far.

**Comment by jm-observer** [comment]
> I run into the same yesterday, and was able to work around it using the following hints:
> 
> 我昨天也遇到了同样的情况，并且能够通过以下提示来解决它:
> 
> https://prototype-kernel.readthedocs.io/en/latest/bpf/troubleshooting.html
> 
> This indicates that the operation might fail due to `RLIMIT_MEMLOCK ` being too low. I tried changing the limit system wide via `ulimit -l`, but that didn't work (only allowed to increase the limit). Then I read through some threads like https://bbs.archlinux.org/viewtopic.php?id=244525 and figured out I can increase it by editing `/etc/security/limits.conf`. Placing the following line there and logging in again as `so root` increased the limit (one can confirm via running `ulimit -l`) and makes my aya example run (at least as root user):
> 
> 这表明操作可能由于 RLIMIT _ MEMLOCK 太低而失败。我尝试通过 ulimit-l 在整个系统范围内更改限制，但是这不起作用(只允许增加限制)。然后我通读了一些线程，比如 https://bbs.archlinux.org/viewtopic.php?id=244525，发现我可以通过编辑/etc/security/limit s.conf 来增加它。将下面的代码行放在那里，然后再次登录，这样 root 用户就增加了限制(可以通过运行 ulimit-l 来确认) ，并使我的 aya 示例运行(至少作为 root 用户) :
> 
> ```
> root             -       memlock         131072
> ```
> 
> As the first link mentioned, it might also be fixable via calling [setrlimit](https://man7.org/linux/man-pages/man2/setrlimit.2.html) in the application - but I didn't investigate that further so far.
> 
> 正如第一个链接所提到的，它也可以通过在应用程序中调用 setrlimit 来修复——但是到目前为止我还没有进一步研究这个问题。

Good job! thanks a lot! I'll try it sometime
