### ISSUE TITLE
bpf: LPMTrie needs to be created with flag BPF_F_NO_PREALLOC

### ISSUE THREAD

**Issue by dave-tucker** [aya-rs/aya#332]
Here: https://github.com/aya-rs/aya/blob/main/bpf/aya-bpf/src/maps/lpm_trie.rs#L40
And in any other constructor for this map, we should add `BPF_F_NOPREALLOC` if not already provided.

This is to avoid getting an `-EINVAL` on map creation.
See: https://github.com/torvalds/linux/blob/9e6b19a66d9b6b94395478fe79c5a3ccba181ad3/kernel/bpf/lpm_trie.c#L551

**Comment by chenhengqi** [comment]
I would like to work on this issue.
