### ISSUE TITLE
Rename aya-bpf* to aya-ebpf*

### ISSUE THREAD

**Issue by alessandrod** [aya-rs/aya#333]
We should s/bpf/ebpf/ across all crates, and this is about aya-bpf.

The bpf crates should be renamed to aya-ebpf*. Since this is going to break everything, it should come with a semver bump, and the release notes (and probably the book somewhere?) should point to https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml to help people migrate.

**Comment by ishitatsuyuki** [comment]
I feel this change is rather pointless. libbpf is named libbpf and not libebpf. The eBPF community use these two terms interchangeably to a large degree, and I don’t think there’s a demand nor benefit to changing the name.

**Comment by alessandrod** [comment]
When I submitted the bpf* rustc targets, they were almost dismissed by some since people thought it was actually bpf and not ebpf, and they said we should probably have ebpf targets intead. Whenever I blog or tweet about aya and related efforts, someone *always* gets confused by bpf vs ebpf. Do not assume that because you're part of a community that uses a language, people gravitating around or outside the community share your knowledge and understand the language.
