### ISSUE TITLE
Support setting priority for classifier programs

### ISSUE THREAD

**Issue by anfredette** [aya-rs/aya#358]
The SchedClassifier attach function does not currently allow the priority (aka preference) of a classifier program to be explicitly set.  Instead, the underlying netlink_qdisc_attach function defaults the priority to zero which tells the system to assign it the next highest priority for the given qdisc.  It is useful to be able to explicitly control the order in which filters are executed and also to be able to insert new filters into an existing set at less than the highest priority.

**Comment by vadorovsky** [comment]
It's done, closing
