### ISSUE TITLE
aya_log_ebpf cannot print to screen in LSM program

### ISSUE THREAD

**Issue by fanrong1992** [aya-rs/aya#362]
I try to run example in [aya/book](https://aya-rs.dev/book/programs/lsm/), but after I execute `renice 1 -p 380074`, there is no output on screen.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/16589152/184112105-0431ca20-0f23-49a2-ac64-b9d4a48df1f8.png">
It works well in kprobe program.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/16589152/184112352-6928bf0c-c626-4d15-be2e-2aa62c213b1c.png">
Here is my code:
``` rust
#![no_std]
#![no_main]

use aya_bpf::{
    cty::c_int,
    macros::lsm,
    programs::LsmContext,
};
use aya_log_ebpf::{debug, info};
mod vmlinux;
use vmlinux::task_struct;

#[no_mangle]
static PID: i32 = 0;

#[lsm(name="task_setnice")]
pub fn task_setnice(ctx: LsmContext) -> i32 {
    match unsafe { try_task_setnice(ctx) } { 
        Ok(ret) => ret,
        Err(ret) => ret,
    }   
}

unsafe fn try_task_setnice(ctx: LsmContext) -> Result<i32, i32> {
    info!(&ctx, "function task_setnice called");
    let p: *const task_struct = ctx.arg(0);
    let nice: c_int = ctx.arg(1);
    let ret: c_int = ctx.arg(2);

    if ret != 0 { 
        return Err(ret);
    }   

    if (*p).pid == 380074 && nice < 0 { 
        return Err(-1);
    }   
    Ok(0)
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! { 
    unsafe { core::hint::unreachable_unchecked() }
}
```
Is there any bug in aya_log_ebpf or my code? Thank you~

**Comment by pplanel** [comment]
This example (LSM task_setnice) is working for you? It does not work for me, none LSM app.

**Comment by pplanel** [comment]
As discussed in Discord, i got Aya LSM example working on Ubuntu Lemmy by edit `GRUB_CMDLINE_LINUX` on `/etc/default/grub`:

`GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1
lsm=lockdown,capability,yama,appar      mor,bpf bpf_lsm=1"`

and then:
`$ sudo update-grub`

reboot

**Comment by fanrong1992** [comment]
> This example (LSM task_setnice) is working for you? It does not work for me, none LSM app.

It doesn't work for me, either.

**Comment by fanrong1992** [comment]
> As discussed in Discord, i got Aya LSM example working on Ubuntu Lemmy by edit `GRUB_CMDLINE_LINUX` on `/etc/default/grub`:
> 
> `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1 lsm=lockdown,capability,yama,apparmor,bpf bpf_lsm=1"`
> 
> and then: `$ sudo update-grub`
> 
> reboot

Thank you for your solution, I will try it.

**Comment by vadorovsky** [comment]
I'm closing this. Now we have an explanation in docs how to enable BPF LSM - https://aya-rs.dev/book/programs/lsm/#ensure-that-bpf-lsm-is-enabled
