### ISSUE TITLE
Allow the user to load pre-existing BPF maps from a pin point or a Raw FD 

### ISSUE THREAD

**Issue by astoycos** [aya-rs/aya#385]
Similar to https://github.com/cilium/ebpf 's Map APIs https://pkg.go.dev/github.com/cilium/ebpf#LoadPinnedMap and https://pkg.go.dev/github.com/cilium/ebpf#NewMapFromFD I would like the ability to load and interact with Pre-existing BPF maps which may or may not have been loaded by aya.

**Comment by vadorovsky** [comment]
That would be a part of the New Map API #75

**Comment by alessandrod** [comment]
> That would be a part of the New Map API #75

We have actually discussed this on discord with @astoycos and @dave-tucker. The issue isn't super relevant and we should probably close it.
