### ISSUE TITLE
Proposal: Runtime Logging for eBPF Programs

### ISSUE THREAD

**Issue by dave-tucker** [aya-rs/aya#40]
I was thinking about trying to implement a generic logging solution for eBPF programs.

My potentially crazy solution relies on 2 maps:

1. Hashmap for configuration (e.g log-level)
2. Perf Event Array for logs

The way this might work is as follows:

1. Implement a bpf_logger for the [log](https://docs.rs/log/0.4.14/log/index.html) crate. The log level comes from the config map. Messages higher than the log level are discarded while other messages are written to the perf event array. Alternatively, add a similar crate here given the constraints of writing for bpf targets.
2. The userspace application should be able to poll perf event array, read the logs, and direct to somewhere user accessible - e.g stdout/stderr, a file, systemd journal etc...

Then from within your bpf program you can just use the log macros e.g `info!(...)`
This would present a much more comprehensive (and production safe) alternative to #39, at (hopefully) a low cost to overall program size.

**Comment by alessandrod** [comment]
This has been on my todo for a loong time! 

The hard part about this is that last time I tried, `core::fmt` didn't compile for the bpf targets. There are smaller, simpler and almost drop-in replacements for `core::fmt`, so we should probably experiment with those.

**Comment by dave-tucker** [comment]
> The hard part about this is that last time I tried, core::fmt didn't compile for the bpf targets. There are smaller, simpler and almost drop-in replacements for core::fmt, so we should probably experiment with those.

I had a look and couldn't see anything that was really suitable to drop in. Given the 512-byte stack limit and scary reports of huge stack allocations for formatting floating point numbers I think it would be safer to do something like [defmt](https://defmt.ferrous-systems.com).

For example:

1. User initialises a logger `
#[global_logger]
static mut aya_logger::new("my_app");
`
1. User may then use logging macros like `info!`
1. Behind the scenes, the macro writes a struct to a perf_event_array or maybe a ringbuffer
1. In the userspace app, we have a thread polling the perf_event_array that reads the data, formats it and writes to wherever

The struct would be something like:
``` rust
#[repr(C)]
log_message struct {
    timestamp
    log_level: u8,
    message: &[u8],
}
```

So the `info!` macro would take variadic args e.g `info!("oh noes, an error happened when I got some data {}", data)` and the impl would write that as a `&[u8]` in our `log_message_struct` and then pop the message in the array/ringbuffer. The actual formatting would happen in userspace, where we have heap :thinking:

**Comment by alessandrod** [comment]
A first iteration of a logging library is now at https://github.com/aya-rs/aya-log. It uses a per-cpu array to do formatting so it doesn't waste stack space. I'm going to close this now and we can discuss improvements in the aya-log repo.
