### ISSUE TITLE
Add integration tests for BTF relocations

### ISSUE THREAD

**Issue by alessandrod** [aya-rs/aya#412]
We should add integration tests for BTF relocations. These could be one small program written in C for each relocation type (struct field, array field, bitfield, etc). 

Each test should define and load its "target BTF", with the final layout for the thing being relocated and tested. Then it should have a local definition for the thing being relocated with an incompatible layout. The test should check that after relocation, the layout matches the target BTF.

**Comment by shaneutt** [comment]
I'm very interested in giving this a try. My only caveat is that I'm a few weeks out from having time for it as my life is wrapped up in Kubecon right now, so if there's anyone else who needs to take it in the meantime please do. Otherwise my intention will be to have a go at it after Kubecon.

**Comment by tamird** [comment]
Done, I think.
