### ISSUE TITLE
map `AYA_LOGS` not found error

### ISSUE THREAD

**Issue by zz85** [aya-rs/aya#415]
I'm not sure if there're some other factors, but I get this error

```
Error: error opening log event array

Caused by:
    map `AYA_LOGS` not found
```

if `use aya_log_ebpf::info;` is not included in the ebpf program. Adding that line, even if `info!()` isn't used, fix the issue

**Comment by alessandrod** [comment]
When that error happens it means that you've removed `aya_log_ebpf` usage from your ebpf crate, but are still calling `BpfLogger::init` on the userspace side

**Comment by zz85** [comment]
ah this makes sense now, AYA_LOGS is opened inside BpfLogger::init_with_logger(). good to know that  `BpfLogger::init()` doesn't need to be called if ebpf side logging isn't required.
