### ISSUE TITLE
loading BTF invalid BTF type kind 19

### ISSUE THREAD

**Issue by banditopazzo** [aya-rs/aya#419]
Seems I got it since I update the kernel to version 6.0

I thought it was something related to libbpf bindings and tried to re generate the bindings using the last version of libbpf from upstream git repo, but seems to not solve the issue.

@dave-tucker said on Discord that it's related to new btf enum64 type.

**Comment by jiripospisil** [comment]
Hitting the same on `6.1.12-arch1-1` on `main#56c143831e8f056ac77bb5282a340c1a545eb0f2`.

**Comment by alessandrod** [comment]
This was fixed in https://github.com/aya-rs/aya/pull/453
