### ISSUE TITLE
Move aya and related crates to a github organization

### ISSUE THREAD

**Issue by alessandrod** [aya-rs/aya#43]
I think it's time to move aya to an organization. Ideally I'd also move bpf-linker and my WIP rustc fork there to keep everything in one place.

What name should we use? I created github.com/ebpf-rs a while ago, but I'm not so sure about the name anymore. Suggestions welcome!

**Comment by dave-tucker** [comment]
I started playing a game of word association with Rust,  e(Bee)PF and Aya and have a couple of ideas

- ayaka-rs: Ayaka can mean colourful flower... which would attract bees!
- aristaeus: A minor Greek god who kept bees
- devorah-rs: Hebrew word for bee
- thriae or thriai: A bee maiden from Greek mythology
- beekeep-rs
- lutjanus: Genus of fish. Lutjanus aya, was apparently believed to be a type of Red Snapper. And these fish eat crabs. Poor ferris.

**Comment by evilsocket** [comment]
ebpf-rs is nice and functional, but why not just keeping Aya for the org itself?

**Comment by dave-tucker** [comment]
I suspect because https://github.com/aya is (unfortunately) alreadty taken.
So `aya-rs` or some other derivative would be needed.

**Comment by evilsocket** [comment]
oops, i didn't check, my bad :D

**Comment by evilsocket** [comment]
`bee-rs`? who doesn't like 🍻

**Comment by alessandrod** [comment]
I'm leaning towards `aya-rs`. I don't love it but it's simple and it doesn't introduce new names, which I think may be confusing. Unless anyone hates it I'm going to move things over this weekend.
