### ISSUE TITLE
How to manage bpf map only via aya

### ISSUE THREAD

**Issue by nevermosby** [aya-rs/aya#433]
Hi team,

Newbie for aya here. I'd like to manage bpf map only without any bpf program attached. I tried the code below:

```rust
    // init bpf object without any actual bpf program
    let bpf = aya::Bpf::load(&[])?;
    // init map
    let mut array = Array::try_from(bpf.map_mut("ARRAY").unwrap())?;
    array.set(1, 42, 0)?;
    assert_eq!(array.get(&1, 0)?, 42);
    println!("map done");
```
But I got errors below:
```
Error: error parsing BPF object

Caused by:
    0: error parsing ELF data
    1: Could not read file magic

```

The error message does make sense, but I wanna init bpf map without any bpf program. Any ideas?

**Comment by vadorovsky** [comment]
Does your map already exist and was your eBPF program with its definition loaded by sometthing else?

If not, I think you are asking for the impossible. To create maps, you need to load an eBPF object with their definitions.

If yes, that would be definitely possible (I mean - interacting with an already existing map), but we don't support that in Aya. For now, Aya allows you to interact with maps which are defined in the ELF object you load.

**Comment by nevermosby** [comment]
@vadorovsky thx for reply. It looks like I have misunderstood the process of bpf map creation. I will load an eBPF object to do  so. Thank you very much :).
