### ISSUE TITLE
Add MapInfo::from_pinned API like ProgramInfo does

### ISSUE THREAD

**Issue by HypoGump** [aya-rs/aya#448]
I find there are APIs for accessing pinned programs, but for pinned maps, it's not the case
[ProgramInfo::from_pinned](https://docs.rs/aya/latest/src/aya/programs/mod.rs.html#766-791)
[Map::open_pinned](https://docs.rs/aya/latest/src/aya/maps/mod.rs.html#242) (It is `pub(crate)`)

**Comment by vadorovsky** [comment]
It's already done, we have `from_pinned`  and `from_fd` methods here:

https://github.com/aya-rs/aya/blob/main/aya/src/maps/mod.rs#L528-L574

But we just didn't release that yet. If you want to try them out already, you can try using Aya from git, by doing the following.

`Cargo.toml`:

```
[patch.crates-io]
aya = { git = "https://github.com/aya-rs/aya", branch = "main", features = ["async_tokio"] }
```

`[your-userspace-project]
aya =  { git = "https://github.com/aya-rs/aya", branch = "main", features = ["async_tokio"] }
```

But be aware that we changed the entire map API on main branch, so you might need to revamp the most of your code dealing with maps. And since we didn't make a release yet, we didn't document it in the book.
