### ISSUE TITLE
feat(aya-metrics + aya-metrics-ebpf): Add metrics crates to emit metrics from eBPF

### ISSUE THREAD

**Issue by OliverGavin** [aya-rs/aya#465]
This is just an idea I had which I am wondering if it would bring any value to this project and its users.

I am using aya in an XDP program which doesn't really interact with user space - I am mangling packets in XDP driver mode and sending them straight back out using the XDP_TX action. This does however mean that it is difficult to know what the XDP program is doing.

The aya-log and aya-log-ebpf are great for logging - but it could be really cool to do the same thing with metrics.

The proposal is quite simple - just like how aya-log-ebpf provides the logging macros and aya-log connects it into the commonly used log crate - the idea is that aya-metrics-ebpf provides the metric macros and aya-metrics connects it to the commonly used metrics crate.

**Comment by vadorovsky** [comment]
I really like the idea, I would love to see such macros!

That said, I'm not sure if that should be a project under Aya umbrella (at least for now). Logging is an essential thing for programming, therefore we keep aya-log even in the monorepo. But for metrics, there is no hard dependency on Aya during development - metrics macros can be easily implemented in completely separate crates.

I would just implement the idea as a new project. That would also show a strong advantage of Aya - ability to use external crates even in eBPF programs.

**Comment by OliverGavin** [comment]
Great! getting aya-bpf into crates.io would really help with that :)

https://github.com/aya-rs/aya/issues/464

If I can successfully qualify aya for my use case I'll try and get aya-metrics + aya-metrics-ebpf out over the next couple of months or so.

**Comment by vadorovsky** [comment]
Since we agreed that metrics could start in a separate crate, I'm closing this issue and will keep #464 open for the aya-bpf release.
