### ISSUE TITLE
please provide a separate aya_example project for others to wind up faster

### ISSUE THREAD

**Issue by omac777** [aya-rs/aya#5]
I appreciate all efforts you went through all the many pieces to the ebpf puzzle interfacing surrounding tools and kernel along with your use of rust workspaces for separating and building all the different aspects.

Please provide an example project to use aya to allow others to wind up faster.  The one crate doc example shows to load an ebpf .o, but it didn't really elaborate/clarify enough steps for me to do anything practical with aya yet.  I still feel I need to read/master ebpf all C ebpf documentation before taking advantage of aya.

Thank you for listening.  Cheers.

**Comment by alessandrod** [comment]
Yup hang tight, as I mentioned in the announcement, tutorial like guides are coming soon.

**Comment by tamird** [comment]
There is now a bunch of docs, examples, and a cargo template at https://aya-rs.dev/.
