### ISSUE TITLE
lifecyle: Add a `forget()` API for `Link`

### ISSUE THREAD

**Issue by dave-tucker** [aya-rs/aya#51]
Default behaviour is that the `Drop` trait calls `detach()` when the program is terminated (or panics).
For some types of long running programs you may wish to intentionally `forget()` the fd wrapped by `Link`, so you can keep the program running after exit. Query and detach can happen out-of-band for some program types (e.g via netlink, or `bpf_prog_query`)

**Comment by seanyoung** [comment]
I'm not sure it should be called `forget()`, but then again I am struggling to come up with a better name. Maybe something like `keep_program_attached()`, `disown()`, or `keep_attached()`. Maybe I'll come up with a better name.
