### ISSUE TITLE
What's missing for (pure) xdp.frags support?

### ISSUE THREAD

**Issue by brevilo** [aya-rs/aya#516]
The section name `xdp.frags` is currently [not supported](https://github.com/aya-rs/aya/blob/cfa693bc3b4442a8c97cfcd24551ea6439f25e50/aya-obj/src/obj.rs#L163). What's missing to change that? AFAIK, `xdp.frags` does not depend on anything else. Yes, `xdp.frags/cpumap` and `xdp.frags/devmap` probably depend on the new maps themselves being [implemented](https://github.com/aya-rs/aya/pull/292) but `xdp.frags` itself doesn't depend on those, if I'm not mistaken.

Note: XDP multi-buffer (fragment) support is required e.g. when using jumbo frames.

**Comment by dave-tucker** [comment]
Correct. We'd just need to add some logic to translate `xdp.frags` into a an `Xdp` program with the flag `BPF_F_XDP_HAS_FRAGS` set so it gets used at load time.

**Comment by brevilo** [comment]
Thanks, that's what I figured. I might give this a try but it'll take some time as I'm still coming to grips with the Aya internals (and Rust for that matter).

**Comment by dave-tucker** [comment]
No worries! I took care of this in #519 if you want to try it out. It handles the userspace side as well as kernel side.
