### ISSUE TITLE
refactor aya-tool to work without bindgen-cli

### ISSUE THREAD

**Issue by dmitris** [aya-rs/aya#518]
Currently https://aya-rs.dev/book/aya/aya-tool/ says:
> Ensure that you have bpftool and bindgen installed in your system, aya-tool is not going to work without it.

paraphrasing @vadorovsky:
> I'm wondering why at some point we even started to require having bindgen-cli.
I remember that bindgen crate used to be just a library which called its own internals and didn't require cli.
We should check if there is some way to get around the cli dep.

References:
* https://rust-lang.github.io/rust-bindgen/introduction.html
* https://fitzgeraldnick.com/2016/12/14/using-libbindgen-in-build-rs.html

**Comment by alessandrod** [comment]
see https://github.com/aya-rs/aya/issues/95 and https://github.com/aya-rs/aya/pull/297. It's needed so we can pass -- --extra-bindgen-args-here to aya-tool
