### ISSUE TITLE
Relocations are too strict

### ISSUE THREAD

**Issue by marysaka** [aya-rs/aya#533]
I'm trying to make use of struct "flavors" but this cannot work with aya current design.

The following eBPF doesn't load with aya (full reproducer [here](https://github.com/marysaka/aya_struct_flavor_reloc_repro)):
```c
#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

struct task_struct_rh___redhat {
    u64 self_exec_id;
};

struct task_struct___redhat {
    struct task_struct_rh___redhat *task_struct_rh;
};

#define printk(fmt, ...) ({                                    \
        char __fmt[] = fmt;                                    \
        bpf_trace_printk(__fmt, sizeof(__fmt), ##__VA_ARGS__); \
})

SEC("tp/bpf_prog")
int
bpf_prog(
    void *ctx
) {
    struct task_struct *task;
    u64 exec_id;

    task = (struct task_struct *)bpf_get_current_task();
    if (!task) {
        return 0;
    }

    // On CentOS 7 kernel, self_exec_id is part of task_struct_rh.
    if (bpf_core_field_exists(((struct task_struct___redhat *)task)->task_struct_rh)) {
        exec_id = BPF_CORE_READ((struct task_struct___redhat *)task, task_struct_rh, self_exec_id);
    } else {
        exec_id = BPF_CORE_READ(task, self_exec_id);
    }

    printk("bpf_prog exec_id: %lx", exec_id);

    return 0;
}

char LICENSE[] SEC("license") = "GPL";
```

At the time of writing, `aya-obj` will generate a ``MissingTargetDefinition`` error on the relocation for ``task_struct_rh`` in the ``BPF_CORE_READ``.

This behavior differ with what [libbpf does](https://github.com/libbpf/libbpf/blob/5b795f7b3028b125bb0ad1db7dc809297b28094f/src/relo_core.c#L1398-L1408).

Missing relocations at load time shouldn't cause an error in `aya-obj` but instead poison related instructions.

If any of those code-path are taken, the verifier will refuse to load the eBPF.

**Comment by alessandrod** [comment]
Thank you for the report! I see that you forked aya did you want to take a stab at fixing this, or want me to take a look?

**Comment by marysaka** [comment]
> Thank you for the report! I see that you forked aya did you want to take a stab at fixing this, or want me to take a look?

I did a fix with https://github.com/marysaka/aya/commit/6c5a0845a1985068adb897963cbea21b507fcbca but that basically nullify ``ComputedRelocation::compute_*_relocation`` errors.

I don't know if anyone have a usecase/need for those errors, but if it's fine for you I can PR those changes.
