### ISSUE TITLE
Bug in bpf_probe_read_.*_str_bytes helpers

### ISSUE THREAD

**Issue by qjerome** [aya-rs/aya#552]
It seems the returned buffer includes NULL byte, while the documentation claims it does not.
```rust
pub unsafe fn bpf_probe_read_user_str_bytes(
    src: *const u8,
    dest: &mut [u8],
) -> Result<&[u8], c_long> {
    let len = gen::bpf_probe_read_user_str(
        dest.as_mut_ptr() as *mut c_void,
        dest.len() as u32,
        src as *const c_void,
    );
    if len < 0 {
        return Err(-1);
    }

    let len = len as usize;
    if len >= dest.len() {
        // this can never happen, it's needed to tell the verifier that len is
        // bounded
        return Err(-1);
    }

    Ok(&dest[..len]) // ERROR HERE !!!! the len returned by bpf_probe_read_user_str includes NULL byte
}
```

**Comment by qjerome** [comment]
It seems same error has been propagated to `bpf_probe_read_kernel_str_bytes`

**Comment by qjerome** [comment]
On success bpf_probe_read_str returns a **strictly positive length of the string** (according to documentation) so it should be safe just to return Ok(&dest[..len-1])

**Comment by alessandrod** [comment]
Nice catch! Want to make a PR for it?

Where we currently do 

```
    if len >= dest.len() {
        // this can never happen, it's needed to tell the verifier that len is
        // bounded
        return Err(-1);
    }
```

We'll also have to check for `len == 0`. The documentation says it returns a strictly positive length but the verifier doesn't know that.

**Comment by qjerome** [comment]
I can do a PR for it for sure however I think it will be mixed up with my current fork pending PR (https://github.com/aya-rs/aya/pull/530). Is it possible to make a different PR without doing another fork of the project (sorry if that's a silly question I've never been in such a situation) ? You can ping me on the Discord channel if you want to help me out with that aspect.
