### ISSUE TITLE
Handle empty tracefs mount points

### ISSUE THREAD

**Issue by drewvis** [aya-rs/aya#556]
On certain Linux configurations (tested against 5.10) it appears that while `tracefs` is actually mounted at `/sys/kernel/debug/tracing`, it may also create an empty directory at `/sys/kernel/tracing` for unknown reasons. This behavior confuses the current logic in `find_tracefs_path` here: https://github.com/aya-rs/aya/blob/3e9d85f8715737865495a16435615074bf8b3df9/aya/src/programs/utils.rs#L27-L42

This code simply checks if the directory exists and will later fail when no traces are found since  `/sys/kernel/tracing` is empty. I will add a PR that adds a check to see if the mount is empty so the correct path is discovered.

**Comment by drewvis** [comment]
A more robust solution would likely be getting the true mount point of `tracefs` from `/proc/mounts` but I believe at least verifying the mount point is not empty will suffice for now.

**Comment by alessandrod** [comment]
Thanks for reporting this! The fix looks good, however before we merge it I think it would be good to understand _why_ `/sys/kernel/tracing` exists and is empty?

**Comment by drewvis** [comment]
Good idea, I tracked down the docs from kernel.org (https://www.kernel.org/doc/Documentation/trace/ftrace.txt) and it looks like there's an explanation:

```
When tracefs is configured into the kernel (which selecting any ftrace
option will do) the directory /sys/kernel/tracing will be created. To mount
this directory, you can add to your /etc/fstab file:
 tracefs       /sys/kernel/tracing       tracefs defaults        0       0
```

So it looks like in some cases, (In Amazon Linux 2 this is the default behavior) tracefs will only mount at `/sys/kernel/debug/tracing`. However, the kernel will still create the directory  `/sys/kernel/tracing`. The user is often expected to manually mount the directory in order for it to exist in ` /sys/kernel/tracing` according to the documentation. 

Without the fix from this PR, aya will fail to load tracepoint style programs on systems where the kernel is configured with ftrace options but `/sys/kernel/tracing` was not previously mounted.

**Comment by alessandrod** [comment]
Perfect, would you mind adding a comment next to the code that summarizes this? Also add the link above so we remember where it comes from

**Comment by drewvis** [comment]
Added some comments explaining the overall issue as well as the link to the docs to the PR.
