### ISSUE TITLE
cannot init environment

### ISSUE THREAD

**Issue by sergey-safarov** [aya-rs/aya#576]
I want to execute `cargo install --no-default-features --features system-llvm bpf-linker` on the Fedora 37 dist and got this error.

```
   Compiling llvm-sys v160.0.2
   Compiling simplelog v0.7.6
   Compiling clap_derive v4.2.0
   Compiling thiserror-impl v1.0.40
error: No suitable version of LLVM was found system-wide or pointed
              to by LLVM_SYS_160_PREFIX.
       
              Consider using `llvmenv` to compile an appropriate copy of LLVM, and
              refer to the llvm-sys documentation for more information.
       
              llvm-sys: https://crates.io/crates/llvm-sys
              llvmenv: https://crates.io/crates/llvmenv
   --> /home/safarov/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-160.0.2/src/lib.rs:490:1
    |
490 | / std::compile_error!(concat!(
491 | |     "No suitable version of LLVM was found system-wide or pointed
492 | |        to by LLVM_SYS_",
493 | |     env!("CARGO_PKG_VERSION_MAJOR"),
...   |
500 | |        llvmenv: https://crates.io/crates/llvmenv"
501 | | ));
    | |__^

error: could not compile `llvm-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bpf-linker v0.9.6`, intermediate artifacts can be found at `/tmp/cargo-installT0PSGV`
```

Latest avaialble LLVM version is
```
[safarov@safarov-dell ~]$ llvm-config --version
15.0.7
```
Can we update the instruction on how force use `llvm-sys` for `llvm 15` instead of `llvm-sys-160.0.2`.

**Comment by alessandrod** [comment]
Are you building on anything other than x86? Otherwise you should build with:

```
cargo install bpf-linker
```

which instructions are you following?

**Comment by vadorovsky** [comment]
We can't lower the LLVM version. It matches exactly the same LLVM version as Rust nightly is using internally. Also, we want to be as up-to-date as possible.

We are planning to solve the problem (of lack of up-to-date LLVM packages) by providing binary builds of bpf-linker (with cargo binstall).

**Comment by sergey-safarov** [comment]
> Are you building on anything other than x86?

yes, used `x86_64`.
I have changed dist where is present `llvm16` and now able to compile `bpf-linker`.
