### ISSUE TITLE
does aya-bpf support atomic operation?

### ISSUE THREAD

**Issue by Sherlock-Holo** [aya-rs/aya#588]
https://docs.kernel.org/bpf/instruction-set.html#atomic-operations says there are some atomic operations can be used in ebpf

so can we use [AtomicU32](https://doc.rust-lang.org/core/sync/atomic/struct.AtomicU32.html) and others in ebpf codes? does aya-bpf suport it?

**Comment by alessandrod** [comment]
You can't use any of the high level `Atomic*` since the ebpf platform doesn't provide all the required primitives to implement those. You _can_ use the low level intrinsics `core::instrinsics::atomic_*`.  Only the ones actually implemented in the llvm BPF backend can be used.
