### ISSUE TITLE
Hello XDP run with map error

### ISSUE THREAD

**Issue by liyan-ah** [aya-rs/aya#609]
I am following [hello XDP!](https://aya-rs.dev/book/start/hello-xdp/) and get this error:
```
cargo xtask run
Error: map error

Caused by:
    0: failed to create map `AYA_LOGS` with code -1
    1: Operation not permitted (os error 1)
Failed to run `sudo -E target/debug/myapp`
```
and with `sudo`, still get this error:
```
sudo target/debug/myapp
Error: map error

Caused by:
    0: failed to create map `AYA_LOG_BUF` with code -1
    1: Operation not permitted (os error 1)
```
any ideas?

**Comment by alessandrod** [comment]
can you run `sudo RUST_LOG=debug target/debug/myapp`?

**Comment by liyan-ah** [comment]
> sudo RUST_LOG=debug target/debug/myapp

```
sudo RUST_LOG=debug target/debug/myapp
[2023-05-23T12:48:15Z DEBUG aya::bpf] [FEAT PROBE] BPF program name support: false
[2023-05-23T12:48:15Z DEBUG aya::bpf] [FEAT PROBE] BTF support: true
[2023-05-23T12:48:15Z DEBUG aya::bpf] [FEAT PROBE] BTF func support: true
[2023-05-23T12:48:15Z DEBUG aya::bpf] [FEAT PROBE] BTF global func support: false
[2023-05-23T12:48:15Z DEBUG aya::bpf] [FEAT PROBE] BTF var and datasec support: true
[2023-05-23T12:48:15Z DEBUG aya::bpf] [FEAT PROBE] BTF float support: false
[2023-05-23T12:48:15Z DEBUG aya::bpf] [FEAT PROBE] BTF decl_tag support: false
[2023-05-23T12:48:15Z DEBUG aya::bpf] [FEAT PROBE] BTF type_tag support: false
Error: map error

Caused by:
    0: failed to create map `AYA_LOGS` with code -1
    1: Operation not permitted (os error 1)
```

**Comment by liyan-ah** [comment]
anything wrong with `BTF` configuration?

**Comment by liyan-ah** [comment]
> can you run `sudo strace -o strace.log target/debug/myapp` and paste the content of strace.log here?

```
sudo strace -o strace.log target/debug/myapp
Error: map error

Caused by:
    0: failed to create map `AYA_LOGS` with code -1
    1: Operation not permitted (os error 1)
```

**Comment by liyan-ah** [comment]
The `strace.log` is very long. And the main operation that caused this error maybe this:
```
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_PERF_EVENT_ARRAY, key_size=4, value_size=4, max_entries=128, map_flags=0, inner_map_fd=0, map_name="AYA_LOGS", map_ifindex=0, btf_fd=0, btf_key_type_id=0, btf_value_type_id=0}, 144) = -1 EPERM (Operation not permitted)
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x55c7ff5cbb88, FUTEX_WAKE_PRIVATE, 1) = 1
```

**Comment by liyan-ah** [comment]
Besides, `bpftrace` works okay.

**Comment by liyan-ah** [comment]
@alessandrod 
Any advice ?

**Comment by alessandrod** [comment]
Can you paste the output of 

```
cat /sys/devices/system/cpu/possible
cat /sys/devices/system/cpu/online
```

**Comment by alessandrod** [comment]
Can you also paste the output of `ulimit -a`

**Comment by liyan-ah** [comment]
> Can you also paste the output of `ulimit -a`

```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2061377
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2061377
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by liyan-ah** [comment]
> Can you paste the output of
> 
> ```
> cat /sys/devices/system/cpu/possible
> cat /sys/devices/system/cpu/online
> ```

```
$ cat /sys/devices/system/cpu/possible
0-127

$ cat /sys/devices/system/cpu/online
0-127
```

**Comment by liyan-ah** [comment]
@alessandrod

**Comment by liyan-ah** [comment]
@marysaka 
any ideas?

**Comment by zaoying** [comment]
The eBPF maps uses locked memory, which is default very low. Your program likely need to increase resource limit RLIMIT_MEMLOCK see system call [setrlimit(2)](http://man7.org/linux/man-pages/man2/setrlimit.2.html).

The bpf_create_map call will return errno EPERM (Operation not permitted) when the RLIMIT_MEMLOCK memory size limit is exceeded.

**Comment by zaoying** [comment]
By rasing max locked memory, I have solved this problem

```sh
sudo vi /etc/security/limits.conf
```

add a new line  `*   hard   memlock    655360` ，then relogin ssh or reboot, the problem is gone.

**Comment by liyan-ah** [comment]
> By rasing max locked memory, I have solved this problem
> 
> ```shell
> sudo vi /etc/security/limits.conf
> ```
> 
> add a new line `* hard memlock 655360` ，then relogin ssh or reboot, the problem is gone.

Thanks for your reply.
I use `cilium-ebpf` as well, and `cilium` would use
```
// Allow the current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal(err)
}
```
to remove memlock. Does `aya` has such handles? Maybe it would be better if add memory limit remove handle in example code.

**Comment by zaoying** [comment]
> > By rasing max locked memory, I have solved this problem
> > ```shell
> > sudo vi /etc/security/limits.conf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > add a new line `* hard memlock 655360` ，then relogin ssh or reboot, the problem is gone.
> 
> Thanks for your reply. I use `cilium-ebpf` as well, and `cilium` would use
> 
> ```
> // Allow the current process to lock memory for eBPF resources.
> 	if err := rlimit.RemoveMemlock(); err != nil {
> 		log.Fatal(err)
> }
> ```
> 
> to remove memlock. Does `aya` has such handles? Maybe it would be better if add memory limit remove handle in example code.

Rust itself has `rlimit` crate，you can set resource limit by yourself. here is the example:

1. add `rlmit` crate to `Cargo.toml`

```toml
[dependencies]
rlimit = "0.9.1"
```

2. add below code to `userspace` code

```rust
use rlimit::Resource;

const DEFAULT_SOFT_LIMIT: u64 = 4 * 1024 * 1024;
const DEFAULT_HARD_LIMIT: u64 = 8 * 1024 * 1024;

pub fn set_relimit() -> Result<(), Error>{
    Resource::MEMLOCK.set(DEFAULT_SOFT_LIMIT, DEFAULT_HARD_LIMIT)
}
```

**Comment by liyan-ah** [comment]
> 

Thanks a lot.

**Comment by liyan-ah** [comment]
Here is my workable solution:
```
// myapp/myapp/Cargo.toml
rlimit = "0.9.1"

// myapp/myapp/src/main.rs
use rlimit::Resource;
#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let opt = Opt::parse();
    env_logger::init();

    if !Resource::MEMLOCK
        .set(rlimit::INFINITY, rlimit::INFINITY)
        .is_ok()
    {
        warn!("cannot remove mem lock");
    }
```

And my solution is involved in https://github.com/aya-rs/aya-template/pull/94.

Hope it would help.
