### ISSUE TITLE
integration test documentation requires update

### ISSUE THREAD

**Issue by dave-tucker** [aya-rs/aya#670]
The old documented workflow in `test/README.md` was:

`cargo xtask integration-test --libbpf-dir ../../libbpf`

Since then:
- `--libbpf-dir` has been deprecated
- A checkout of libbpf is no longer required
- There appear to have been changes to the way the command handles rust toolchains since `cargo xtask integration test` fails

```
--- stderr
  error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
  See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
  thread 'main' panicked at '"cargo" "build" "-p" "integration-ebpf" "-Z" "build-std=core" "--release" "--message-format=json" "--target" "bpfel-unknown-none" "--target-dir" "/home/dave/dev/aya-rs/aya/target/debug/build/integration-test-3d3491ef010ffd35/out/integration-ebpf" exited with status code 101:
  ', test/integration-test/build.rs:215:25
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: error while building userspace application
```

The only working command I've found is:
```console
cargo +nightly xtask integration-test
```

Which may or may not be the intended workflow.

**Comment by ajwerner** [comment]
> --libbpf-dir has been deprecated

This is no longer mentioned.

> A checkout of libbpf is no longer required

https://github.com/aya-rs/aya/pull/673

> There appear to have been changes to the way the command handles rust toolchains since cargo xtask integration test fails

https://github.com/aya-rs/aya/pull/674

**Comment by ajwerner** [comment]
Fixed by https://github.com/aya-rs/aya/pull/673 and https://github.com/aya-rs/aya/pull/674.
