### ISSUE TITLE
Separate KProbe and KRetProbe

### ISSUE THREAD

**Issue by addisoncrump** [aya-rs/aya#700]
There's a potential footgun currently where a developer may attempt to access arguments in a kretprobe (clobbered by function) or access return value in a kprobe (doesn't exist yet). Since this is effectively always incorrect, kprobe and kretprobe should be split and `args`/`ret` access be limited to their respective types.

**Comment by tyrone-wu** [comment]
Hi! 👋 In regards to how `kprobe` and `kretprobe` should be split, would this also include splitting `ProbeContext` (or defining new context types, such as `ProbeContext` and `RetProbeContext`)? 
Also, would `uprobe` and `uretprobe` need to be split as well? 

Sorry if this question is off the mark with how ebpf works. I'm still sort of a newbie with the inner workings of these specific contexts.

**Comment by alessandrod** [comment]
Hey! 👋 All good questions 😊

Yes to both: uprobe and uretprobe would need to be split as well, and I guess we'd need separate ProbeContext and RetProbeContext.
