### ISSUE TITLE
Make a macro similar to BPF_PROG

### ISSUE THREAD

**Issue by vadorovsky** [aya-rs/aya#71]
The cool thing about libbpf is that it defines the `BPF_PROG` macro which allows to provide typed arguments which are unpacked from the BPF program context:

https://elixir.bootlin.com/linux/v5.14.13/source/tools/lib/bpf/bpf_tracing.h#L381

So far aya doesn't provide such a macro and all aya-based BPF programs are unpacking the context by manually providing offsets, like:

https://github.com/alessandrod/aya-echo-tracepoint/blob/main/echo-ebpf/src/main.rs#L35-L36

It would be nice to have some macro which takes sized types and does the unpacking with offset automatically, without necessity of doing that manually.

**Comment by willfindlay** [comment]
What about something like `LsmContext::argument(n: usize)` that unpacks argument `n` as a `*const T`? Though I believe this would only work in BTF programs like tp_btf/fentry/fexit/lsm. Others would still need to go through `bpf_probe_read`.

**Comment by alessandrod** [comment]
> What about something like `LsmContext::argument(&self, n: usize)` that unpacks argument number `n` as a `*const T`? Though I believe this would only work in BTF programs like tp_btf/fentry/fexit/lsm. Others would still need to go through `bpf_probe_read`.

Yes something like that is what I had in mind. As you mentioned different contexts have different requirements when it comes to accessing args, so I don't think we'll be able to expose exactly the same API across contexts, but we should aim to be as consistent as possible.

**Comment by vadorovsky** [comment]
> > @alessandrod @vadorovsky More concretely, I was thinking of something like the snippet below. This could be re-implemented for other context types as needed or behind some new trait (perhaps `BtfContext`?). Seems to work well so far. The only annoying bit is that downcasting to an integer as in `int ret` for example is a little bit awkward. WDYT?
> 
> Are LSM ctx arguments actually _always_ pointers, or is it just the libbpf macro that casts everything to `void *`? It also seems to cast `pt_regs` registers to `void *` but obviously you can have other types in registers (eg integers).

LSM ctx arguments are mostly pointers, only sometimes they are primitive types like `int`, `unsigned int` or `pid_t`.

Here are the signatures of all of them:

https://github.com/torvalds/linux/blob/master/include/linux/lsm_hook_defs.h

(arguments of LSM hooks start after the 3rd parameter of `LSM_HOOK` macro)

**Comment by alessandrod** [comment]
> But anyway, even with `int` arguments in LSM hooks, unpacking them with `BPF_PROG` works. Example:

It works because the macro seems to turn on -Wno-int-conversion, and so the pointer to inter conversion happens implicitly. Rust doesn't have such an implicit conversion, I think we should try to find a way to make this work for both `*const T` and `T`.

**Comment by willfindlay** [comment]
For non-BTF program types, I was also thinking we could have two alternatives for reading arguments. One that simply uses `bpf_probe_read` to read the value into an allocated variable, and another that lets you read it into a scratch buffer defined by an eBPF map (probably makes more sense for this map to be provided explicitly by the user). That should pretty much cover every use case I think.

**Comment by willfindlay** [comment]
Based on the discussion in Discord, it sounds like we've landed on the following:
- A helper (likely part of the `BpfContext` trait) implemented for each program type:
  - In non-BTF programs, it uses `bpf_probe_read` to copy the argument onto the stack
  - In BTF programs, it simply casts the argument to a pointer to the type (still not sure about how we will handle primitives without an explicit cast by the user)
- An `aya_deref!` macro which can be used to chain derefs in BTF programs and transparently call `bpf_probe_read` in non-BTF programs

**Comment by vadorovsky** [comment]
Not needed anymore, since we have already have a sane way of unpacking arguments.
