### ISSUE TITLE
Building hello world XDP program fails

### ISSUE THREAD

**Issue by aboullaite** [aya-rs/aya#787]
Hello Aya maintainers,

I was trying to run a freshly created aya XDP program in a docker container, however, after many attemps, I keep getting `thread 'main' panicked at 'failed to run the command: Os { code: 2, kind: NotFound, message: "No such file or directory" }', xtask/src/run.rs:64:10`

### Steps to reproduce:
In a linux machine, run `docker run --rm -it --privileged -h lb --name lb --env TERM=xterm-color aboullaite/xdp-lb:latest` this should prompt a new docker container with everything setup. 
Create a new aya XDP program from template: `cargo generate --name test -d program_type=xdp https://github.com/aya-rs/aya-template`

Access the new created file `cd test` and try to build/run it `USER=root cargo generate --name demo -d program_type=xdp https://github.com/aya-rs/aya-template`

###### Expected behaviour
Program should start a xdp program
###### Current behaviour
Program fails with error `thread 'main' panicked at 'failed to run the command: Os { code: 2, kind: NotFound, message: "No such file or directory" }', xtask/src/run.rs:64:10`

**Comment by vadorovsky** [comment]
Try with

```
--security-opt seccomp=unconfined
```

```
docker run --rm -it --privileged --security-opt seccomp=unconfined -h lb --name lb --env TERM=xterm-color aboullaite/xdp-lb:latest
```

**Comment by steveoni** [comment]
> Try with
> 
> ```
> --security-opt seccomp=unconfined
> ```
> 
> ```
> docker run --rm -it --privileged --security-opt seccomp=unconfined -h lb --name lb --env TERM=xterm-color aboullaite/xdp-lb:latest
> ```

@aboullaite does this solution work for you? i tried thesame and I'm still getting thesame error

here is my dockerfile

```dockerfile
# Stage 1: Build stage
FROM ubuntu:latest AS builder

# Define the build argument with a default value
ARG PLATFORM=linux/amd64

# Install necessary packages for building bpftool and Rust dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    linux-headers-generic \
    libelf-dev \
    libpcap-dev \
    binutils-dev \
    git \
    curl \
    pkg-config \
    libssl-dev \
    libffi-dev \
    zlib1g-dev \
    cmake \
    ninja-build \
    clang \
    llvm \
    lld

# Clone and build bpftool
RUN git clone --recurse-submodules https://github.com/libbpf/bpftool.git && \
    cd bpftool/src && make

# Copy the built bpftool to the correct location
RUN cp ./bpftool/src/bpftool /usr/local/bin/bpftool

# Stage 2: Final image
FROM ubuntu:latest

# Define the build argument with a default value
ARG PLATFORM=linux/amd64

# Install necessary runtime packages and Rust environment
RUN apt-get update && apt-get install -y \
    libelf1 \
    linux-tools-common \
    git \
    curl \
    gcc \
    libssl-dev \
    libffi-dev \
    zlib1g-dev \
    build-essential \
    libzstd-dev \
    bash \
    wget \
    gnupg \
    lsb-release \
    software-properties-common



RUN bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" && \
    apt-get install -y libpolly-18-dev

# Set up the PATH for LLVM 18
ENV PATH="/usr/lib/llvm-18/bin:$PATH"

# Install Rust and Cargo
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# Set environment variable for Rustup path
ENV PATH="/root/.cargo/bin:${PATH}"

# Copy bpftool from the builder stage
COPY --from=builder /usr/local/bin/bpftool /usr/local/bin/bpftool

RUN cargo install cargo-binstall 

#&& cargo binstall cargo-generate | sh -s -- -y

# Create TUN device (if needed)
RUN mkdir -p /dev/net && mknod /dev/net/tun c 10 200 && chmod 0666 /dev/net/tun

# Set default command (optional)
CMD ["tail", "-f", "/dev/null"]

```

**system**: I'm running this docker on MacBook m1 pro

I ran this docker using docker-compose

```yaml
version: "3.8"
services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLATFORM: linux/amd64
    volumes:
      - ./codes:/codes
    privileged: true
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    ports:
      - "8080:8080"
      - "3200:3200"
    entrypoint: ["tail", "-f", "/dev/null"]
```

and also using the same command as the solution above

```
docker run --rm -it --privileged --security-opt seccomp=unconfined -v ./codes:/codes -h lb --name lb --env TERM=xterm-color network-tuntap-my_service
```

I still get thesame error

```
  Finished `dev` profile [unoptimized + debuginfo] target(s) in 13.26s
thread 'main' panicked at xtask/src/run.rs:49:10:
failed to run the command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by steveoni** [comment]
> --security-opt seccomp=unconfined

dixed

**Comment by aboullaite** [comment]
@steveoni sorry for the late reply. Were you able to fix it? It is maybe worth documenting your steps as well for future reference

**Comment by steveoni** [comment]
> @steveoni sorry for the late reply. Were you able to fix it? It is maybe worth documenting your steps as well for future reference

It was an issue from my docker setup. By default,  the setup does not have audio command and the  cargo xtask run default args specified sudo and this causes the panic.
