### ISSUE TITLE
Raw tracepoint link id type cannot be imported

### ISSUE THREAD

**Issue by KiranWells** [aya-rs/aya#833]
The raw tracepoint attach function returns the `RawTracePointLinkId` type. However, this type seems to be private within the `aya::programs::raw_trace_point` module and cannot be imported into an application that uses Aya. This prevents them from being used as function arguments or return values, preventing code from passing these link IDs around; for example, to allow another function to detach the probe.

If the type is intentionally private (for example, it cannot be moved or is not `Send`/`Sync`), it would be helpful to have that in the documentation. Otherwise, I think it should be public in either `aya::programs` or `aya::programs::raw_trace_point` to allow it to be named directly in user code.

**Comment by tamird** [comment]
We should probably enable the unreachable pub item lint.

**Comment by alessandrod** [comment]
I think that `raw_trace_point` is accidentally non-pub? Most modules are pub, for some reason a handful aren't. I think we should make them all pub.
