### ISSUE TITLE
Publish aya-obj crate to crates.io

### ISSUE THREAD

**Issue by Stringy** [aya-rs/aya#835]
Hi folks, 

I'm looking to use the aya-obj crate to dynamically identify extension programs in a BPF object file, and use that information during loading, but it doesn't look like there's much of it reexported via the main aya crate (unless I am very much mistaken.) The README implies that this is available for use despite its internal-api origins.

I was wondering if there was an intended way of using the crate directly, or whether it could be published to crates.io?

**Comment by vadorovsky** [comment]
Honestly we were intending not to publish it in the near future, the reason being that we would rather not commit for having a stable API in aya-obj just yet. For now, I would recommend to use it as a git dependency, if that's sufficient for your use case (Aya is being used as a git dependency nowadays anyway).

Just my personal opinion, but I would be in favor of releasing aya-obj (maybe as a 0.0.1, to not give an impression that we are commiting for stable API) as soon as we are going to release new Aya, according to https://github.com/aya-rs/aya/milestone/3. I'd also do the same with all *-ebpf crates.

**Comment by alessandrod** [comment]
> I would be in favor of releasing aya-obj (maybe as a 0.0.1, to not give an impression that we are commiting for stable API) as soon as we are going to release new Aya

This is basically what we decided last time we talked about it. We just need someone to finish the s/bpf/ebpf/ rename and pull the trigger on it

**Comment by Stringy** [comment]
> For now, I would recommend to use it as a git dependency, if that's sufficient for your use case
Yes this should be fine I think, and certainly enough for the prototype I'm building. Thanks!

> We just need someone to finish the s/bpf/ebpf/ rename and pull the trigger on it
Is this something I can help out with? I see there's an existing PR, but if there's more to do I'd be happy to muck in

**Comment by vadorovsky** [comment]
> > I would be in favor of releasing aya-obj (maybe as a 0.0.1, to not give an impression that we are commiting for stable API) as soon as we are going to release new Aya
> 
> This is basically what we decided last time we talked about it. We just need someone to finish the s/bpf/ebpf/ rename and pull the trigger on it

Fair enough, I will just do necessary changes in Dave's PR (resolve conflicts and push).

**Comment by sanmai-NL** [comment]
@vadorovsky Can you hyperlink to said Dave's PR?

**Comment by vadorovsky** [comment]
> @vadorovsky Can you hyperlink to said Dave's PR?

https://github.com/aya-rs/aya/pull/528

@dave-tucker would you mind rebasing? I will do my best to review and try to get it in. Or I can also take it over.
