### ISSUE TITLE
Call unwrap on Result<(), c_long> will cause relocating error

### ISSUE THREAD

**Issue by Spedoske** [aya-rs/aya#856]
https://github.com/Spedoske/aya-issue-1/commit/6cd7ad24132c5a4b5482caf2d2787413b0158432

Run with `RUST_LOG=info cargo xtask run` will get.

```
Finished dev [unoptimized + debuginfo] target(s) in 1.89s
Error: error relocating function

Caused by:
    0: error relocating `foo`
    1: function 0x48 not found while relocating `foo`
Failed to run `sudo -E target/debug/foo
```

It will run if I just discard the `Result<(), c_long>` (without unwrapping it).

`Linux nixos 6.1.55 #1-NixOS SMP PREEMPT_DYNAMIC Sat Sep 23 09:11:13 UTC 2023 x86_64 GNU/Linux`

**Comment by dave-tucker** [comment]
This is expected behaviour - your eBPF code can't panic.
This is somewhat documented here: https://aya-rs.dev/book/#ebpf-program-constraints
Unfortunately, there isn't an easy way to catch this at compile time :(
