### ISSUE TITLE
Dependency Hijacking risk due to Crate Name Change

### ISSUE THREAD

**Issue by LeChatP** [aya-rs/aya#910]
The crate "aya-bpf" has been renamed "aya-ebpf" in #528. This major modification poses a significant security risk due to potential dependency hijacking. If an attacker takes the old crate name, projects relying on it may inadvertently include malicious code, without being noticed, ref [mitre](https://attack.mitre.org/techniques/T1195/001/).

Proposed Actions to mitigate the potential attack:

* **Claim the aya-bpf dependency before it is stolen** And associate an obsolete version to warn developers.

**Comment by ziggoon** [comment]
The crates are defined through git repositories, not crates.io so I don't think there is an inherent risk of dependency hijacking in this case, but correct me if I'm wrong.

```
[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya" }
```

**Comment by LeChatP** [comment]
Indeed, my bad; I am too security-matrixed about every modification.
