### ISSUE TITLE
Instructions on codegen

### ISSUE THREAD

**Issue by kevinji** [aya-rs/aya#914]
How do you get `cargo +nightly xtask codegen` to work? I'm running into a bunch of missing header files on aarch64 Ubuntu (as a VM on macOS) so I'm wondering if there's instructions to get codegen working.

**Comment by tyrone-wu** [comment]
Hello! 👋
I just made a PR #917  that should fix the current issue for this. Also, these packages need to be installed as well for codegen to work. 
```bash
sudo apt-get install libc6-dev libc6-dev-{arm64,armel,riscv64}-cross
```
This should probably be documented somewhere since I only found this when looking through the codegen GHA workflow.
