### ISSUE TITLE
How about supporting for searching the symbols file from the gnu.debuglink section?

### ISSUE THREAD

**Issue by swananan** [aya-rs/aya#936]
Hi, I recently used aya to write some eBPF programs for tracing user programs. In my scenario, the release version is stripped, and the symbol file's relative path is placed in the _gnu.debuglink_ section. Unfortunately, aya doesn't currently support finding symbols from the _gnu.debuglink_ section, in my opinion, which is a pretty common use case. I've made some changes locally to support this small feature in my test environment. I'm wondering if there have been any plans or developments for adding this feature upstream. If needed, I'm happy to raise a PR for this.

**Comment by alessandrod** [comment]
Hi! Yes I would love to see support for debuglink, and ideally for build_id too :)

**Comment by WindySha** [comment]
Is it possible to support symbol in .gnu_debugdata section ? For Android platform, many elf symbols are hidden in .gnu_debugdata section.
